# Generated by Django 4.2.10 on 2024-02-24 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VoyageVault', '0002_homepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Homepage',
        ),
    ]
