# Generated by Django 4.2.10 on 2024-02-24 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VoyageVault', '0004_travelplace_user_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Activity Name')),
                ('activity_url', models.URLField(blank=True)),
                ('description', models.TextField(verbose_name='Description')),
                ('rating', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], verbose_name='Rating')),
            ],
        ),
        migrations.RemoveField(
            model_name='travelentry',
            name='image_url',
        ),
        migrations.DeleteModel(
            name='EntryDetail',
        ),
        migrations.AddField(
            model_name='activity',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='VoyageVault.travelentry'),
        ),
    ]
