# Generated by Django 4.2.10 on 2024-02-24 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VoyageVault', '0005_activity_remove_travelentry_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='activity_url',
        ),
        migrations.AddField(
            model_name='activity',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='activity_images/'),
        ),
    ]
