# Generated by Django 4.2.10 on 2024-02-24 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('VoyageVault', '0003_delete_homepage'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplace',
            name='user_profile',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='VoyageVault.userprofile'),
        ),
    ]
